### ISSUE TITLE
On Windows, was able to view but not now

### ISSUE THREAD

**Issue by tyeeman** [fxnn/gone#32]
I ran gone.exe and was able to view/edit. Then I tried exporting templates, restarted gone and now I can't even see any page, even after deleting .templates folder and restarting gone. I gave full permissions under Windows properties to gone.exe but still I get "Oops, unauthorized" in the browser and "no read permissions" from the command line. What to do?

Update - I was not using the correct url, now it works.

Question - Is Gone for use online from a server? Can servers run Go apps like this?

**Comment by fxnn** [comment]
Yes, it is designed to be used as webserver, online. While I do not regard it production ready from a feature point of view, I do actually use it for serving a website for a while now, and so far, it's stable and reliable.

Glad you could resolve your issue. Feel free to ask any further questions or give feedback!

**Comment by tyeeman** [comment]
Lately I'm using Netlify for web hosting, I'll have to see if they support go apps. Do you use some special web host?

**Comment by fxnn** [comment]
I read that Netlify serves static websites, which probably means that they will not run executables, PHP and whatsoever.

I use virtual machines, like you get them from Amazon AWS. My website runs on a VM of the German hoster Contabo.
